#exceptions handlings
numero1 = 2
numero2 = 5
numero2 = '4'

try:
    print(numero1+numero2)
     
except:
    print('se a producido un error')